version: 2
general:
  branches:
    only:
      master
      develop
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm run build
       - run: npm test
